[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
paste = "1.0.15"

[dev-dependencies]
paste = "1.0.15"
indoc = "2.0.5"
